export const ForgotPassword = "Forgot password?"
export const ReturnToLogin = "Return to Login"
export const LogintoContinue = "Login to Continue"
export const UsernameorEmail = "Username or Email"
export const Email = "Email"
export const Continue = "Continue"
export const ResetPassword = "Reset Password"
export const Password = "Password"
export const NewPassword = "New Password"
export const ConfirmPassword = "Confirm New Password"
export const DeviceCheckpoint = "Device Checkpoint"
export const Login = "Login"
export const Account = "Account";
export const Apicredentials = "Account API"
export const SSHkey = "SSH Keys"
export const Activity = "Activity"
export const Servers = "Servers";
export const Console = "Console";
export const Filemanager = "File managers";
export const Databases = "Databases";
export const Schedules = "Schedules";
export const Users = "Users";
export const Backups = "Backups";
export const Network = "Network";
export const Startup = "Startup";
export const Settings = "Settings";
export const showing_others_servers = "Showing others servers";
export const showing_your_servers = "Showing your servers";
export const there_are_no_other_servers_to_display = "There are no other servers to display";
export const there_are_no_servers_associated_with_your_account = "There are no servers associated with your account";
export const Name = "Name";
export const Allocation = "Allocation";
export const Status = "Status";
export const Suspended = "Suspended";
export const Installing = "Installing";
export const Connecting = "Connecting";
export const Transferring = "Transferring";
export const Type_a_command = "Type a command";
export const Server_is_installing = "This server is currently running its installation process and most actions are unavailable.";
export const Server_is_transferred = "This server is currently being transferred to another node and all actions are unavailable.";
export const Node_is_maintenance = "The node this server is currently on is currently under maintenance and all actions are unavailable.";
export const New_file = "New file";
export const Seems_empty = "This directory seems to be empty.";
export const Limited_to_250 = "This directory is too large to display in the browser, limiting the output to the first 250 files.";
export const Upload = "Upload";
export const Archive = "Archive";
export const Delete = "Delete";
export const Edit = "Edit";
export const Move = "Move";
export const Rename = "Rename";
export const Drag_and_drop = "Drag and drop files to upload.";
export const File_name = "File Name"
export const New_location = "New"
export const New_directory = "Enter the new name and directory of this file or folder, relative to the current directory.";
export const Create_directory = "Create Directory"
export const Created_as = "This directory will be created as"
export const Valied_directory = "A valid directory name must be provided."
export const Save_content = "Save content";
export const Create_file = "Create file";
export const Create_database = "Create Database";
export const Delete_database = "Delete Database";
export const Cancel = "Cancel";
export const No_databases = "It looks like you have no databases.";
export const Cannot_databases = "Databases cannot be created for this server.";
export const New_task = "New Task";
export const Last_run = "Last run at";
export const Next_run = "Next run at";
export const Minute = "Minute";
export const Hour = "Hour";
export const Day = "Day";
export const Week = "Week";
export const Month = "Month";
export const No_subusers = "It looks like you don't have any subusers.";
export const New_user = "New User";
export const Create_backups = "Create Backup";
export const Back_a_page = "Looks like we've run out of backups to show you, try going back a page."
export const No_backups = "It looks like there are no backups currently stored for this server."
export const Cant_made = "Backups cannot be created for this server because the backup limit is set to 0."